# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chicagosalaries.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChicagoSalaries(object):
    def setupUi(self, ChicagoSalaries):
        ChicagoSalaries.setObjectName("ChicagoSalaries")
        ChicagoSalaries.resize(719, 735)
        self.centralwidget = QtWidgets.QWidget(ChicagoSalaries)
        self.centralwidget.setObjectName("centralwidget")
        self.table_salary = QtWidgets.QTableWidget(self.centralwidget)
        self.table_salary.setGeometry(QtCore.QRect(15, 2, 695, 481))
        self.table_salary.setMaximumSize(QtCore.QSize(16777215, 507))
        self.table_salary.setObjectName("table_salary")
        self.table_salary.setColumnCount(4)
        self.table_salary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_salary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salary.setHorizontalHeaderItem(3, item)
        self.table_salary.horizontalHeader().setStretchLastSection(True)
        self.table_salary.verticalHeader().setDefaultSectionSize(73)
        self.group_search = QtWidgets.QGroupBox(self.centralwidget)
        self.group_search.setGeometry(QtCore.QRect(17, 498, 435, 173))
        self.group_search.setObjectName("group_search")
        self.formLayoutWidget = QtWidgets.QWidget(self.group_search)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 25, 415, 147))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_position = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_position.setObjectName("label_position")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_position)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_department = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_department.setObjectName("label_department")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_department)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_salary = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_salary.setObjectName("label_salary")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_salary)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_salary_min = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_salary_min.setObjectName("label_salary_min")
        self.horizontalLayout.addWidget(self.label_salary_min)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.label_salary_max = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_salary_max.setObjectName("label_salary_max")
        self.horizontalLayout.addWidget(self.label_salary_max)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.button_search = QtWidgets.QPushButton(self.centralwidget)
        self.button_search.setGeometry(QtCore.QRect(472, 524, 125, 43))
        self.button_search.setObjectName("button_search")
        ChicagoSalaries.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChicagoSalaries)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ChicagoSalaries.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChicagoSalaries)
        self.statusbar.setObjectName("statusbar")
        ChicagoSalaries.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(ChicagoSalaries)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ChicagoSalaries)
        self.actionQuit.triggered.connect(ChicagoSalaries.close)
        QtCore.QMetaObject.connectSlotsByName(ChicagoSalaries)

    def retranslateUi(self, ChicagoSalaries):
        _translate = QtCore.QCoreApplication.translate
        ChicagoSalaries.setWindowTitle(_translate("ChicagoSalaries", "MainWindow"))
        self.table_salary.setSortingEnabled(True)
        item = self.table_salary.horizontalHeaderItem(0)
        item.setText(_translate("ChicagoSalaries", "Name"))
        item = self.table_salary.horizontalHeaderItem(1)
        item.setText(_translate("ChicagoSalaries", "Position Title"))
        item = self.table_salary.horizontalHeaderItem(2)
        item.setText(_translate("ChicagoSalaries", "Department"))
        item = self.table_salary.horizontalHeaderItem(3)
        item.setText(_translate("ChicagoSalaries", "Salary"))
        self.group_search.setTitle(_translate("ChicagoSalaries", "Search by"))
        self.label_name.setText(_translate("ChicagoSalaries", "Name"))
        self.label_position.setText(_translate("ChicagoSalaries", "Position"))
        self.label_department.setText(_translate("ChicagoSalaries", "Department"))
        self.label_salary.setText(_translate("ChicagoSalaries", "Salary"))
        self.label_salary_min.setText(_translate("ChicagoSalaries", "Minimum"))
        self.label_salary_max.setText(_translate("ChicagoSalaries", "Maximum"))
        self.button_search.setText(_translate("ChicagoSalaries", "search"))
        self.menuFile.setTitle(_translate("ChicagoSalaries", "File"))
        self.actionQuit.setText(_translate("ChicagoSalaries", "Quit"))

